In [1]:
%pip install plotly

Note: you may need to restart the kernel to use updated packages.


In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import os 
import plotly.graph_objects as go

In [18]:
src = '.\\S3.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = list(map(int,data.strip().split('\n')))
fig = go.Figure()

trace = go.Scattergl(
    x=[i for i in range(len(data))],
    y=data,
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Test(Raw).html', auto_open=True)


In [53]:
src = '.\\teraterm.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = list(map(int,data.strip().split('\n')))
fig = go.Figure()

trace = go.Scattergl(
    x=[i for i in range(len(data))],
    y=data,
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Singleslits(Raw).html', auto_open=True)


In [20]:
src = '.\\teraterm.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = smooth(list(map(int,data.strip().split('\n'))))
fig = go.Figure()

trace = go.Scattergl(
    x=[i for i in range(len(data))],
    y=[1/i for i in data],
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Brightness"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Singleslits.html', auto_open=True)


In [17]:
src = '.\\teraterm2.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = list(map(int,data.strip().split('\n')))
fig = go.Figure()


trace = go.Scattergl(
    x=[i for i in range(len(data))],
    y=data,
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits2(Raw).html', auto_open=True)


In [187]:
src = '.\\teraterm2.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = smooth(list(map(int,data.strip().split('\n'))),3)
fig = go.Figure()

err = 1/max(data)
trace = go.Scattergl(
    x=[i for i in range(len(data))],
    y=[1/i-err for i in data],
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits2.html', auto_open=True)


In [212]:
src = '.\\teraterm3.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = smooth(list(map(int,data.strip().split('\n'))),3)
fig = go.Figure()

err = 1/max(data)
trace = go.Scattergl(
    x=[i-13263 for i in range(len(data))][13263-5000:13263+5000],
    y=[1/(i)-err for i in data][13263-5000:13263+5000],
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits3(Raw).html', auto_open=True)


In [213]:
x=[i-13263 for i in range(len(data))][13263-5000:13263+5000]
y=[1/(i)-err for i in data][13263-5000:13263+5000]
x.pop(5000)
y.pop(5000)

0.000662723462067366

In [249]:
popt, pcov = curve_fit(inteference,x, y,p0=[650*10**(-9),0.00015,0.00015,2.57],bounds=([0,0,0,0],[np.Inf,np.Inf,np.Inf,np.Inf]),maxfev=5000)

In [245]:
popt, pcov = curve_fit(inteference,x, y,p0=[650*10**(-9),0.00015,0.00015,2.57],bounds=([650*10**(-9)*0.95,0.00015*0.95,0.00015*0.95,2.57*0.95],[650*10**(-9)*1.05,0.00015*1.05,0.00015*1.05,2.57*1.05]))

In [250]:
popt

array([8.58103566e-06, 1.64010868e-03, 3.36665748e-04, 1.95909518e+00])

In [248]:
src = '.\\teraterm3.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = smooth(list(map(int,data.strip().split('\n'))),3)
fig = go.Figure()

err = 1/max(data)
trace = go.Scattergl(
    x=[i-13263 for i in range(len(data))][13263-5000:13263+5000],
    y=[1/(i)-err for i in data][13263-5000:13263+5000],
    mode='markers',
    name= 'data',
)
trace_fit = go.Scattergl(
    x=[i for i in range(-5000,5000)],
    y=[inteference(i,650*10**(-9),0.00015,0.00015,2.57) for i in range(-5000,5000)],
    mode='lines+markers',
    name= 'fit',
)
fig.add_trace(trace_fit)
fig.add_trace(trace)



Xaxis_title = "Displacement(index)"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits3(REG).html', auto_open=True)


In [8]:
src = '.\\teraterm4.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = list(map(int,data.strip().split('\n')))
fig = go.Figure()

trace = go.Scattergl(
    x=[i for i in range(len(data))],
    y=data,
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits4.html', auto_open=True)


In [5]:

def smooth (data,mask):
    return[sum(data[i:i+mask])/mask for i in range(len(data)-mask+1)]



In [5]:
def inteference(x,lmbda,d,a,distance):
    sin_theta = abs(indexToM(x)/distance)
    return 0.001056063*(np.cos((np.pi*d*sin_theta)/lmbda)**2*(np.sin((np.pi*a*sin_theta)/lmbda)/((np.pi*a*sin_theta)/lmbda))**2)

In [17]:
def indexToM(index):
    return (212/26)*10**(-3)*(index*1.8)/360

In [182]:
popt, pcov = curve_fit(inteference, smooth(x,3), smooth(y,3),p0=[650*10**(-9),0.00015,0.00015,2.50],bounds=([0,0,0,0],[np.Inf,np.Inf,np.Inf,np.Inf]),maxfev=5000)

In [183]:
popt

array([1.22601178e-05, 1.47228736e-03, 1.93735666e-04, 9.84679827e-01])

In [28]:
src = '.\\teraterm2.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

def inteference(x,lmbda,d,a,distance):
    sin_theta = abs(indexToM(x)/distance)
    return 0.001056063*(np.cos((np.pi*d*sin_theta)/lmbda)**2*(np.sin((np.pi*a*sin_theta)/lmbda)/((np.pi*a*sin_theta)/lmbda))**2)

data = smooth(list(map(int,data.strip().split('\n'))),3)
fig = go.Figure()

err = 1/max(data)
trace = go.Scattergl(
    x=[indexToM(i-11176) for i in range(len(data))],
    y=[(1/i)-err for i in data],
    mode='markers',
    name= 'data',
)
trace_fit = go.Scattergl(
    x=[indexToM(i-11176) for i in range(len(data))],
    y=[inteference(i-11176,670*10**(-9),1*10**(-3),0.15*10**(-3),2.45) for i in range(len(data))],
    mode='lines+markers',
    name= 'fit',
)
fig.add_trace(trace_fit)
fig.add_trace(trace)



Xaxis_title = "Displacement(cm)"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits2(REG).html', auto_open=True)


C:\Users\NIGHTL~1\AppData\Local\Temp/ipykernel_13892/2608343036.py:8: RuntimeWarning:

invalid value encountered in double_scalars



In [34]:
src = '.\\teraterm3.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = smooth(list(map(int,data.strip().split('\n'))),3)
fig = go.Figure()

def inteference(x,lmbda,d,a,distance):
    sin_theta = abs(indexToM(x)/distance)
    return 662.7235*10**(-6)*(np.cos((np.pi*d*sin_theta)/lmbda)**2*(np.sin((np.pi*a*sin_theta)/lmbda)/((np.pi*a*sin_theta)/lmbda))**2)

offset_x = 13263
err = 1/max(data)
trace = go.Scattergl(
    x=[i-offset_x for i in range(len(data))],
    y=[(1/i)-err for i in data],
    mode='markers',
    name= 'data',
)
trace_fit = go.Scattergl(
    x=[i-offset_x for i in range(len(data))],
    y=[inteference(i-offset_x,670*10**(-9),1*10**(-3),0.15*10**(-3),2.45) for i in range(len(data))],
    mode='lines+markers',
    name= 'fit',
)
fig.add_trace(trace_fit)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits3(REG).html', auto_open=True)


C:\Users\NIGHTL~1\AppData\Local\Temp/ipykernel_13892/3791360186.py:11: RuntimeWarning:

invalid value encountered in double_scalars



In [12]:
src = '.\\teraterm3.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = smooth(list(map(int,data.strip().split('\n'))))
fig = go.Figure()

trace = go.Scattergl(
    x=[i for i in range(len(data))],
    y=data,
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits3(Smooth).html', auto_open=True)


In [ ]:
src = '.\\teraterm3.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = smooth(list(map(int,data.strip().split('\n'))))
fig = go.Figure()

trace = go.Scattergl(
    x=[i for i in range(len(data))],
    y=data,
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)

trace_fit = go.Scattergl(
    x=[i-11176 for i in range(len(data))],
    y=[inteference_2(i-11176,popt[0],popt[1],popt[2]) for i in range(len(data))],
    mode='lines+markers',
    name= 'fit',
)
fig.add_trace(trace)

Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits3(Smooth).html', auto_open=True)



In [13]:
src = '.\\teraterm4.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = smooth(list(map(int,data.strip().split('\n'))))
fig = go.Figure()

trace = go.Scattergl(
    x=[i for i in range(len(data))],
    y=data,
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits4(Smooth).html', auto_open=True)


In [16]:
%pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [20]:
from scipy.optimize import curve_fit

In [9]:
def func(x, a):
    return a * x+1023

In [3]:
import numpy as np

In [33]:
def translate(data,popt):
    var = float(np.cos(np.arctan(popt)))
    return list(map(lambda x:x*var,data))

In [14]:
src = '.\\teraterm.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = np.array(list(zip([i for i in range(len(data))],smooth(list(map(int,data.strip().split('\n')))))))
popt, pcov = curve_fit(func, data[:,0], data[:,1])
theta = np.arctan(popt[0])/57.296
data = np.matmul(data,[[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])
fig = go.Figure()

trace = go.Scattergl(
    x=data[:,0],
    y=[1/i for i in data[:,1]],
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Singleslits(Rotated).html', auto_open=True)


In [21]:
src = '.\\teraterm2.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = np.array(list(zip([i for i in range(len(data))],smooth(list(map(int,data.strip().split('\n')))))))
popt, pcov = curve_fit(func, data[:,0], data[:,1])
theta = np.arctan(popt[0])/57.296
data = np.matmul(data,[[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])
fig = go.Figure()

trace = go.Scattergl(
    x=data[:,0],
    y=data[:,1],
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits2(Rotated).html', auto_open=True)


TypeError: smooth() missing 1 required positional argument: 'mask'

In [22]:
src = '.\\teraterm3.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = np.array(list(zip([i for i in range(len(data))],smooth(list(map(int,data.strip().split('\n'))),3))))
popt, pcov = curve_fit(func, data[:,0], data[:,1])
theta = np.arctan(popt[0])/57.296
data = np.matmul(data,[[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])
fig = go.Figure()

trace = go.Scattergl(
    x=data[:,0],
    y=data[:,1]*-1+1023,
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits3(Rotated).html', auto_open=True)


NameError: name 'func' is not defined

In [46]:
src = '.\\teraterm4.log'
sample_file = open(os.path.join(src))
data = sample_file.read()
sample_file.close()

data = np.array(list(zip([i for i in range(len(data))],smooth(list(map(int,data.strip().split('\n')))))))
data = np.matmul(data,[[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])
fig = go.Figure()

trace = go.Scattergl(
    x=data[:,0],
    y=data[:,1],
    mode='markers',
    name= 'data',
)
fig.add_trace(trace)



Xaxis_title = "Displacement"
Yaxis_title = "Volt"
fig['layout'].update(width=960,height=720,xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )


fig.write_html('Doubleslits4(Rotated).html', auto_open=True)


[-0.00255992]


In [37]:
print(float(np.cos(np.arctan(0.0622722))))

0.9980667074704188


In [17]:
np.array(list(zip([1,2],[3,4])))

array([[1, 3],
       [2, 4]])

array([3, 8])

In [16]:
np.matmul(np.array([[1,2],[4,5],[7,8]]),np.array([[3,4],[5,6]]))

array([[13, 16],
       [37, 46],
       [61, 76]])